version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: gps_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    container_name: gps_postgres
    environment:
      POSTGRES_USER: cesar
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: gpsdb
    ports:
      - "5433:5432"

  geolocation:
    build:
      context: .
      dockerfile: GeolocationService/Dockerfile
    depends_on:
      - redis
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  routing:
    build:
      context: .
      dockerfile: RoutingService/Dockerfile
    depends_on:
      - redis
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  audit:
    build:
      context: .
      dockerfile: AuditService/Dockerfile
    depends_on:
      - postgres
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
