apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geolocation
  template:
    metadata:
      labels:
        app: geolocation
    spec:
      containers:
      - name: geolocation
        image: ghcr.io/cesarkortez/monitoreogps-geolocation:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: geolocation-svc
spec:
  selector:
    app: geolocation
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: routing
  template:
    metadata:
      labels:
        app: routing
    spec:
      containers:
      - name: routing
        image: ghcr.io/cesarkortez/monitoreogps-routing:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: routing-svc
spec:
  selector:
    app: routing
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
      - name: audit
        image: ghcr.io/cesarkortez/monitoreogps-audit:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: audit-svc
spec:
  selector:
    app: audit
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
